import os
import subprocess
def LvInfo():
	os.system("lsblk")

def LvExtend():
	VolumeGroupName = input("Enter Volume Group Name : ")
	print("\n")
	LvName = input("Enter Logical volume Name : ")
	print("\n")
	LvSize = input("Enter Logical Volume Extend Size : ")
	print("\n")
	LvExtend = subprocess.getoutput("lvextend --size +{} /dev/{}/{}".format(LvSize,VolumeGroupName,LvName))
	print("[ Logical Volume Extended Successfully ]**************************************************************************")
	print(LvExtend)
	ResizeLv = subprocess.getoutput("resize2fs /dev/{}/{}".format(VolumeGroupName,LvName))
	os.system("lsblk")

def LvReduce():
	VolumeGroupName = input("Enter Volume Group Name : ")
	print("\n")
	LvName = input("Enter Logical volume Name : ")
	print("\n")
	MountPonit = input("Enter Mount Point To Link with Lv : ")
	print("\n")
	LvSize = input("Enter Logical Volume Reduce Size : ")

	OfflineLv = subprocess.getoutput("umount /{}".format(MountPonit))
	print("[ Logical Partition Offline ]**************************************************************************************\n")
	ScanLvPart = os.system("e2fsck -f /dev/mapper/{}-{}".format(VolumeGroupName,LvName))
	print("[ Scan Part ]*****************************************************************************************************\n")
	ResizeLv = os.system("resize2fs /dev/mapper/{}-{}".format(VolumeGroupName,LvName))
	print("[ Format Part ]***************************************************************************************************\n")
	LvReduce = os.system("echo y | lvreduce --size {} /dev/mapper/{}-{}".format(LvSize,VolumeGroupName,LvName))
	print("[ Reduce Logical Volume ]*****************************************************************************************\n")
	MountLv = os.system("mount /dev/{}/{} /{}".format(VolumeGroupName,LvName,MountPonit))
	print("[ Mount Logical Volume ]******************************************************************************************\n")
	os.system("lsblk")


def LvCreate():
	Disk1 = input("Enter Disk 1 : ")
	Disk2 = input("Enter Disk 2 : ")
	os.system("tput setaf 10")
	print("[ Physical Volume Created ]***************************************************************************************")
	Pvcreate1 = os.system("echo y | pvcreate /dev/{}".format(Disk1))
	PvDisplay1 = os.system("echo y | pvdisplay /dev/{}".format(Disk1))
	Pvcreate2 = os.system("echo y | pvcreate /dev/{}".format(Disk2))
	PvDisplay2 = os.system("echo y | pvdisplay /dev/{}".format(Disk2))
	os.system("tput setaf 15")
	print("\n")


	VolumeGroupName = input("Enter Volume Group Name : ")
	VolumeGroup = subprocess.getoutput("vgcreate {} /dev/sdb1 /dev/sdc1".format(VolumeGroupName))
	print(VolumeGroup)
	os.system("vgdisplay {}".format(VolumeGroupName))
	print("[ VolumeGroup Created ]*******************************************************************************************")
	print("\n")

	LvName = input("Enter Logical volume Name : ")
	print("\n")
	LvSize = input("enter Logical volume Size : ")
	Lvcreate = subprocess.getoutput("lvcreate --size +{} --name {} {} -y".format(LvSize,LvName,VolumeGroupName))
	print(Lvcreate)
	os.system("lvdisplay {}/{}".format(VolumeGroupName,LvName))
	print("[ Logical Volume Create ]*****************************************************************************************")
	print("\n")
	FormatType = input("Enter Format Type :")
	print("\n")
	FormatLV = subprocess.getoutput("mkfs.{} /dev/{}/{}".format(FormatType,VolumeGroupName,LvName))
	print("[ Logical Volume Formated Successfully ]***************************************************************************\n")
	MountPonit = input("Enter Mount Point To Link with Lv : ")
	os.system("mkdir /{}".format(MountPonit))
	print("[ Logical Volume Mounted Succesfully ]*****************************************************************************")

	MountLVMPart = os.system("mount /dev/{}/{} /{}".format(VolumeGroupName,LvName,MountPonit))
	os.system("lsblk")

def RemoveLVM():
	print("Logical Volume Name*********************************************************************************")
	os.system("lvs")
	print("Volume Groups Name**********************************************************************************")
	os.system("vgs")
	print("Physical Volumes Name")
	os.system("pvs")
	print("\n\n")
	LvName = input("Enter LV Name : ")
	VgName = input("Enter VG Name : ")
	Pv1Name = input("Enter PV Name : ")
	Pv2Name = input("Enter PV Name : ")
	os.system("lvremove /dev/{}/{}".format(VgName,LvName))
	os.system("vgremove {}".format(VgName))
	os.system("pvremove /dev/{}".format(Pv1Name))
	os.system("pvremove /dev/{}".format(Pv2Name))

#LvReduce()
#LvExtend()
#LVM()